spring:
  application:
    name: ron-movie-ribbon-without-eureka
server:
  port: 7001

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true

ron-provicer-user:
  ribbon:
    listOfServers: localhost:8001