spring:
  application:
    name: ron-movie-ribbon-with-hystrix-propagation
server:
  port: 8014
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true