server:
  port: 8031
spring:
  application:
    name: ron-hystrix-turbine2
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: RON-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2
  appConfig: ron-consumer-movie-ribbon-with-hystrix2
  
turbine.instanceUrlSuffix.RON-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2: /ribbon/hystrix.stream

logging: 
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG