server:
  port: 8031
spring:
  application:
    name: ron-hystrix-turbine3
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: RON-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX3
  appConfig: ron-consumer-movie-ribbon-with-hystrix3
  
logging: 
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG