spring:
  application:
    name: ron-consumer-movie-feign-customizing-hystrix
server:
  port: 9002
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.ron.seekers.spring.service.UserFeignClient: DEBUG

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
