server:
  port: 8761
security:
    user:
      name: user
      password: 123456
eureka:
  datacenter: cloud
  environment: product
  client:
    service-url:
     defaultZone: http://user:123456@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false


